package org.example.sms.types;

public enum RegexPattern {
    CUSTOMER_ID_PATTERN, EMPLOYEE_ID_PATTERN, SUPPLIER_ID_PATTERN,
    ITEM_ID_PATTERN, NAME_PATTERN, CONTACT_PATTERN,
    SALARY_PATTERN, ADDRESS_PATTERN, DOUBLE_PATTERN,
    INT_PATTERN, CUSTOMER_NIC_OLD_PATTERN, CUSTOMER_NIC_NEW_PATTERN
}
